### ISSUE TITLE
[The Hiker] Environment temperature

### ISSUE THREAD

**Issue by fdnuka** [sw21-tug/Team_28#5]
As a user,
I want the Hiker app to provide me with the ambient temperature so when I click on the 'Ambient temperature' button on the main screen it should open another screen which should be split in vertical half. The upper half should contain the icon of the temperature and the text 'Ambient temperature'. Icon goes up and the name stays under the icon. The bottom part shows the temperature of the ambient in Celsius degree. The temperature should be updated every time the user opens that screen. 
Since the ambient temperature is not supported in some Android smartphones, show the button 'Ambient temperature' **only if** the smartphone supports this feature.

**Comment by SebastianGrief** [comment]
Example on how to use the SensorManager. [1]
The constant to use for ambient temp. [2]

The SensorManager.getDefaultSensor() will return null if no sensor available on device. Use that to set the visibility of the button to Visibility.Gone in the main menu. (Do not use Visibility.Invisible because the button will still take up room in the menu [3])

[1] https://developer.android.com/guide/topics/sensors/sensors_environment
[2] https://developer.android.com/reference/android/hardware/Sensor#TYPE_AMBIENT_TEMPERATURE
[3] https://developer.android.com/reference/android/view/View#GONE
