### ISSUE TITLE
[The Hiker] Position on map

### ISSUE THREAD

**Issue by fdnuka** [sw21-tug/Team_28#6]
When user click on the 'Find me' button on the main screen it should open another screen which should be splited in the vertical, with 30% and 70% which will contain the map and the icon with the text. The upper half should contain the icon of the map and the text 'My location'. Icon goes up and the text stays under the icon. In the bottom part show the map and the location of the user.  Update the position on real time.

**Comment by Markus152** [comment]
In order to test this feature the fingerprint of each tester is needed. This will be researched in the next sprint within a follow up ticket and fixed if possible.
According to tutor Stefanie Plasch this is for the first release ok.

The attached file illustrates how to get to the SHA1 key.
![fingerprint](https://user-images.githubusercontent.com/80156264/117155875-74817f00-adbd-11eb-8ec9-cbde5d832830.PNG)
